<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Payment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ec89f85e-92b2-4924-8e3d-929e09c53e93</testSuiteGuid>
   <testCaseLink>
      <guid>30a97c89-05d1-4a27-9324-5e06118bd48e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make A Payment/Add New Payee</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fda9ab1-6990-4155-947e-e3a9aa793f15</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec511067-9496-44c8-ae79-4fcebbaec7a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make A Payment/Make Payment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3d25671-7ee1-45e1-879f-1b557bcf50b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a78c2851-6121-41e4-baa6-4b9f6e6185b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make A Payment/Make Payment more than deposit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92958a87-6816-4f02-bb31-54c488ca648a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
